src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $reponse;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_topic;

    /**
     * @ORM\Column(type="integer")
     */
    private $best_rep;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): self
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getIdTopic(): ?int
    {
        return $this->id_topic;
    }

    public function setIdTopic(int $id_topic): self
    {
        $this->id_topic = $id_topic;

        return $this;
    }

    public function getBestRep(): ?int
    {
        return $this->best_rep;
    }

    public function setBestRep(int $best_rep): self
    {
        $this->best_rep = $best_rep;

        return $this;
    }





}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reponse')
            ->add('id_topic', HiddenType::class, [
                'data' => $options['id'],
            ])
            ->add('best_rep', HiddenType::class, [
                'data' => 0,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
            'id' => '',
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/commentaire')]
class CommentaireController extends AbstractController
{
    #[Route('/', name: 'commentaire_index', methods: ['GET'])]
    public function index(CommentaireRepository $commentaireRepository): Response
    {
        if (!empty($this->getUser())) {
            $inf_roles = $this->getUser()->getRoles();

            if (in_array("ROLE_ADMIN", $inf_roles)) {
                return $this->render('commentaire/index.html.twig', [
                    'commentaires' => $commentaireRepository->findAll(),
                ]);
            } else {
                return $this->redirectToRoute('error');
            }
        } else {
            return $this->redirectToRoute('error');
        }

    }

    #[Route('/new', name: 'commentaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        if (!empty($this->getUser())) {
            $inf_roles = $this->getUser()->getRoles();

            if (in_array("ROLE_ADMIN", $inf_roles)) {
                $commentaire = new Commentaire();
                $form = $this->createForm(CommentaireType::class, $commentaire);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->persist($commentaire);
                    $entityManager->flush();

                    return $this->redirectToRoute('commentaire_index');
                }

                return $this->render('commentaire/new.html.twig', [
                    'commentaire' => $commentaire,
                    'form' => $form->createView(),
                ]);
            } else {
                return $this->redirectToRoute('error');
            }
        } else {
            return $this->redirectToRoute('error');
        }
    }

    #[Route('/{id}', name: 'commentaire_show', methods: ['GET'])]
    public function show(Commentaire $commentaire): Response
    {
        if (!empty($this->getUser())) {
            $inf_roles = $this->getUser()->getRoles();

            if (in_array("ROLE_ADMIN", $inf_roles)) {
                return $this->render('commentaire/show.html.twig', [
                    'commentaire' => $commentaire,
                ]);
            } else {
                return $this->redirectToRoute('error');
            }
        } else {
            return $this->redirectToRoute('error');
        }
    }

    #[Route('/{id}/edit', name: 'commentaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commentaire $commentaire): Response
    {
        if (!empty($this->getUser())) {
            $inf_roles = $this->getUser()->getRoles();

            if (in_array("ROLE_ADMIN", $inf_roles)) {
                $form = $this->createForm(CommentaireType::class, $commentaire);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $this->getDoctrine()->getManager()->flush();

                    return $this->redirectToRoute('commentaire_index');
                }

                return $this->render('commentaire/edit.html.twig', [
                    'commentaire' => $commentaire,
                    'form' => $form->createView(),
                ]);
            } else {
                return $this->redirectToRoute('error');
            }
        } else {
            return $this->redirectToRoute('error');
        }

    }

    #[Route('/{id}', name: 'commentaire_delete', methods: ['DELETE'])]
    public function delete(Request $request, Commentaire $commentaire): Response
    {
        if (!empty($this->getUser())) {
            $inf_roles = $this->getUser()->getRoles();

            if (in_array("ROLE_ADMIN", $inf_roles)) {

                if ($this->isCsrfTokenValid('delete' . $commentaire->getId(), $request->request->get('_token'))) {
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->remove($commentaire);
                    $entityManager->flush();
                }

                return $this->redirectToRoute('commentaire_index');
            } else {
                return $this->redirectToRoute('error');
            }
        } else {
            return $this->redirectToRoute('error');
        }
    }
}

templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commentaire/_form.html.twig
{% if app.user %}
    <form name="commentaire" method="post" class="d-flex flex-column align-items-center mt-5 mb-4">
        <div id="commentaire">
            <div class="mb-2 d-flex flex-column">
                <label for="commentaire_reponse" class="required font-size-5 mb-2">Reponse : </label>
                <textarea class="form-control" id="commentaire_reponse" name="commentaire[reponse]" required="required"style="height: 100px; width: 400px"></textarea>
            </div>
            <input type="hidden" id="commentaire_id_topic" name="commentaire[id_topic]" value="{{ topic.id }}">
            <input type="hidden" id="commentaire_best_rep" name="commentaire[best_rep]" value="0">
            <input type="hidden" id="commentaire__token" name="commentaire[_token]" value="rURjUoIN9ggr4MlxUH95d1u0QxxGdLFs65pO1Z3lc0Q">
        </div>
        <button class="btn btn-outline-primary">{{ button_label|default('Save') }}</button>
        {{ form_row(form._token) }}
    </form>


{% endif %}

templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
    <h1>Commentaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reponse</th>
                <th>Id_topic</th>
                <th>Best_rep</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.reponse }}</td>
                <td>{{ commentaire.idTopic }}</td>
                <td>{{ commentaire.bestRep }}</td>
                <td>
                    <a href="{{ path('commentaire_show', {'id': commentaire.id}) }}">show</a>
                    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commentaire_new') }}">Create new</a>
{% endblock %}

templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('commentaire_index') }}">back to list</a>
{% endblock %}

templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Reponse</th>
                <td>{{ commentaire.reponse }}</td>
            </tr>
            <tr>
                <th>Id_topic</th>
                <td>{{ commentaire.idTopic }}</td>
            </tr>
            <tr>
                <th>Best_rep</th>
                <td>{{ commentaire.bestRep }}</td>
            </tr>
        </tbody>
    </table>

    <a class="text-decoration-none " href="{{ path('commentaire_index') }}">back to list</a>

    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}